# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-07 06:13
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteHoldings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('b_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.Site')),
            ],
        ),
    ]
