# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-07 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_auto_20190607_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
